heat_template_version: 2013-05-23

description: Simple template to deploy a single node

resources:
  node:
    type: OS::IoTronic::Node
    properties:
      code:       "testcode"
      name:       "testname"
      device:     "testdevice"
      mobile:     1
      location:   "3,3,3"     
